# Generated by Django 3.1 on 2023-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystr', models.CharField(max_length=1000, verbose_name='指令')),
                ('flag', models.IntegerField(verbose_name='是否运行')),
                ('posttime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '任务管理',
                'verbose_name_plural': '任务管理',
            },
        ),
    ]
